_wandb:
    value:
        cli_version: 0.21.0
        e:
            b02bhfid2uk8h7aczjwymsu5pc7f7np5:
                codePath: MiniGridEnv\minigrid_q_learning.py
                codePathLocal: MiniGridEnv\minigrid_q_learning.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "838087704576"
                        used: "201100271616"
                email: tahamm3008@gmail.com
                executable: C:\Users\HP\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 587d9ec26f13401ced899ec7730ff20433dae65e
                    remote: https://github.com/tahamm786/Autonomous-Car-Driving-using-Deep-RL.git
                host: TAHA-PC
                memory:
                    total: "16805036032"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\HP\OneDrive\Desktop\SUMMER_INTERN_IVLABS\Autonomous-Car-Driving-using-Deep-RL\MiniGridEnv\minigrid_q_learning.py
                python: CPython 3.11.1
                root: C:\Users\HP\OneDrive\Desktop\SUMMER_INTERN_IVLABS\Autonomous-Car-Driving-using-Deep-RL
                startedAt: "2025-07-17T19:53:12.942797Z"
                writerId: b02bhfid2uk8h7aczjwymsu5pc7f7np5
        m: []
        python_version: 3.11.1
        t:
            "3":
                - 13
                - 16
            "4": 3.11.1
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
alpha:
    value: 0.1
episodes:
    value: 1000
gamma:
    value: 0.95
