_wandb:
    value:
        cli_version: 0.21.0
        e:
            v247efbmtaiogs2yrqtbxli2nfmohflh:
                codePath: MiniGridEnv\minigrid_q_learning.py
                codePathLocal: MiniGridEnv\minigrid_q_learning.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "838087704576"
                        used: "201141596160"
                email: tahamm3008@gmail.com
                executable: C:\Users\HP\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 33be7b84ff987402e6f894a99bc206fdb1b8373d
                    remote: https://github.com/tahamm786/Autonomous-Car-Driving-using-Deep-RL.git
                host: TAHA-PC
                memory:
                    total: "16805036032"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\HP\OneDrive\Desktop\SUMMER_INTERN_IVLABS\Autonomous-Car-Driving-using-Deep-RL\MiniGridEnv\minigrid_q_learning.py
                python: CPython 3.11.1
                root: C:\Users\HP\OneDrive\Desktop\SUMMER_INTERN_IVLABS\Autonomous-Car-Driving-using-Deep-RL
                startedAt: "2025-07-17T19:41:59.130096Z"
                writerId: v247efbmtaiogs2yrqtbxli2nfmohflh
        m: []
        python_version: 3.11.1
        t:
            "3":
                - 13
                - 16
            "4": 3.11.1
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
alpha:
    value: 0.1
episodes:
    value: 1000
gamma:
    value: 0.95
